### ISSUE TITLE
refactor(workbench): refactor children components into containers

### ISSUE THREAD

**Issue by ramfox** [qri-io/desktop#498]
realized I was tackling this without an issue to help track:

Welcome to the refactoring workbench issue. We want to utilize selectors and containers to better structure our workbench component!

### renaming & dataset component conventions
Some components have a 'history' and 'status' version. Usually, when they are materially different aka `Commit` & `CommitHistory`, `MetadataEditor` & `Metadata`, `Readme` & `ReadmeHistory`.

Structure switches internally on whether or not to show the editor or the display. Instead, let's enforce, for now, that there are two different versions of each component, a `COMPONENTEditor` and a `COMPONENT`. So let's refactor Structure into `StructureEditor` and `Structure`

DatasetContainer will get a `location` passed from workbench. This will let it know if it should be showing the `Editor` or display versions of each dataset component.

### todos:

* [x] create selectors for datasets (with and without mutations), status (with and without mutations)
* [x] create `writeWorkingDataset` action that pulls out write calls into one action that can be used for each component container
* [x] rename `Commit` to `CommitEditor` & rename `CommitHistory` to `Commit`
* [x] rename `Readme` to `ReadmeEditor` & rename `ReadmeHistory` to `Readme`
* [x] refactor `ReadmeEditor` into container
* [x] refactor `Readme` into container
* [x] rename `Structure` folder to `Schema`
* [x] rename `FormatConfigFSI` to `FormatConfigEditor` and move into `workbench`
* [x] rename `FormatConfigHistory` to `FormatConfig` and move into `workbench`
* [x] move `Structure.tsx` into `workbench` 
* [x] add `StructureEditor` (container) and refactor out editing from `Structure.tsx` & turn into a container
* [x] refactor `MetadataEditor` into container
* [x] refactor `Metadata` into container
* [x] refactor `Body` into container
* [x] refactor `DatasetComponent` into container
* [x] refactor `CommitDetails` into container
