### ISSUE TITLE
v0.5.0 punchlist

### ISSUE THREAD

**Issue by ramfox** [qri-io/desktop#634]
pulled from @chriswhong's punchlist after dogfooding the latest version of qri desktop

Top Level
- [x] Revisit top-level tab tooltips #646 
- [ ] Prevent selecting text almost everywhere via CSS (this is a desktop app, not a website) (partially addressed in #646)
- [x] Warnings in console (tr cannot be a child of div) #633 

Collection
  - Action Buttons
    - [x] “Create Dataset” should say “New Dataset” #641 
          - Keep until the new dataset flow is complete
  - DataTable (Dataset List)
     - [x] Clicking row actions menu for last row adds height, menu div is hidden by bottom
edge of container
    - [x] Dataset Rename Modal #637 

Bulk Actions #616
  - [x] Wire up Pull Latest  
  - [ ] ~~Wire up Quick Export CSV/Export~~ _pushed to a later release_
  - [x] Wire up Remove - issue [here](https://github.com/qri-io/desktop/issues/636) taken by Alicia

Import Flow  #641
  - [x] Add file picker to New Dataset Modal
  - [x] Drag and drop opens modal with file picker populated
  - [x] Clicking Create Dataset in Modal makes a new dataset

Pull Dataset
  - [x] Modal still says “Add”, but button says “Pull” #646 
  - [x] When pulling another user’s dataset, user lands on workbench with no username/name in the header, and “You are viewing another user’s dataset” message.  Goes away after reload or navigate to collection and back (It looks like the fix for this is to select the HEAD commit immediately after pulling) #638 #635 

Row Actions menu 
- [ ] ~~Add Quick Export CSV~~ _punted to a later release_
- [x] Add Custom Export #643
- [x] Add Pull Latest #650

Status Icons
  - [x] Clicking cloud opens a link even if not published #650

Dataset View
  - [x] Dataset name editing #637
  - [x] Rename by clicking dataset name in workbench #637
  - Action Buttons
    - [x] ~~Add “Quick Export CSV” with dropdown for Custom Export~~ Add Export Button #643
    - [x] Add “Pull Latest” for a dataset I already have that has updates
    - [x] Add “Remove”
  - Viewer
    - Body
      - [x] Pagination broken
  - Editor
    - [x] Editing checked out files - change indicator does not appear in Desktop until after reload qri-io/qri#1554
  - Body
    - [x] Pagination broken #639
    - [ ] Body Update flow
    - [ ] Dragging a body 
  - Commit
    - [ ] Commit editor does not scroll-y, button not visible (needs a y-scrolling div somewhere like other components)
  - [x] Commit message placeholder says “Add a title” #646 

Network This work is in the branch `network-pane-css` but is still a WIP.  Need someone to take over branch. https://github.com/qri-io/desktop/issues/631
  - [x] Center loading spinner
  - Home Styling
    - [x] Font Sizes
    - [x] Use DatasetSummary Component for list display on home
  - Preview
    - [x] Layout improvements
    - [x] Change Clone to Pull

**Comment by b5** [comment]
closed by #656!
